name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build static site
        run: |
          # Create static build directory
          mkdir -p _site
          
          # Copy static assets
          cp -r static/* _site/
          cp -r templates/* _site/
          
          # Copy documentation
          cp README.md _site/
          cp -r docs _site/
          
          # Create index.html from template
          python -c "
          import os
          from flask import Flask, render_template
          
          app = Flask(__name__)
          
          with app.app_context():
              # Render the main dashboard template
              with open('templates/dashboard.html', 'r') as f:
                  template_content = f.read()
              
              # Create a simple index.html
              index_content = '''<!DOCTYPE html>
          <html lang=\"en\">
          <head>
              <meta charset=\"UTF-8\">
              <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
              <title>RationalMarkets - AI Long/Short Investment Club</title>
              <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">
              <link href=\"css/dashboard.css\" rel=\"stylesheet\">
          </head>
          <body>
              <div class=\"container mt-5\">
                  <div class=\"row justify-content-center\">
                      <div class=\"col-md-8 text-center\">
                          <h1 class=\"display-4 mb-4\">🤖 RationalMarkets</h1>
                          <h2 class=\"h3 mb-4\">AI Long/Short Investment Club</h2>
                          <p class=\"lead mb-4\">Educational platform for learning AI disruption investment strategies</p>
                          
                          <div class=\"alert alert-warning\" role=\"alert\">
                              <strong>Educational Platform Notice:</strong> This platform provides general investment information for educational purposes only. Nothing on this platform constitutes personalized investment advice.
                          </div>
                          
                          <div class=\"row mt-5\">
                              <div class=\"col-md-6 mb-4\">
                                  <div class=\"card h-100\">
                                      <div class=\"card-body\">
                                          <h5 class=\"card-title\">🌍 Global Strategy</h5>
                                          <p class=\"card-text\">Learn about AI disruption across US, European, and Asian markets with our unified global strategy.</p>
                                      </div>
                                  </div>
                              </div>
                              <div class=\"col-md-6 mb-4\">
                                  <div class=\"card h-100\">
                                      <div class=\"card-body\">
                                          <h5 class=\"card-title\">🔧 Dual Broker Support</h5>
                                          <p class=\"card-text\">Connect with Alpaca Markets (US) or Swissquote (Global) for hands-on learning experience.</p>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          
                          <div class=\"mt-4\">
                              <a href=\"docs/\" class=\"btn btn-primary btn-lg me-3\">📚 Documentation</a>
                              <a href=\"https://github.com/franksiereveld/RationalMarkets\" class=\"btn btn-outline-secondary btn-lg\">💻 GitHub</a>
                          </div>
                          
                          <div class=\"mt-5\">
                              <h3>🎯 Learning Objectives</h3>
                              <div class=\"row mt-3\">
                                  <div class=\"col-md-4\">
                                      <h6>AI Disruption Analysis</h6>
                                      <p class=\"small\">Understanding which companies benefit vs. suffer from AI advancement</p>
                                  </div>
                                  <div class=\"col-md-4\">
                                      <h6>Portfolio Allocation</h6>
                                      <p class=\"small\">Hands-on experience with long/short position sizing</p>
                                  </div>
                                  <div class=\"col-md-4\">
                                      <h6>Global Markets</h6>
                                      <p class=\"small\">Learning to invest across different exchanges and currencies</p>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              
              <footer class=\"mt-5 py-4 bg-light text-center\">
                  <div class=\"container\">
                      <p class=\"mb-0\">© 2024 RationalMarkets - Educational Platform for AI Investment Strategy Learning</p>
                      <p class=\"small text-muted mt-2\">Not investment advice • Educational purposes only • Consult qualified professionals</p>
                  </div>
              </footer>
              
              <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>
          </body>
          </html>'''
              
              with open('_site/index.html', 'w') as f:
                  f.write(index_content)
          "

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

